### ISSUE TITLE
Add a way to load data from store into RBush

### ISSUE THREAD

**Issue by gkinsman** [dpmcmlxxvi/pouchdb-geospatial#33]
Hi there! Just started using this with pouch and it's such a neat idea and design!

Something I've run into is that when an app restarts or you reload a page, the only way to rebuild the R-Tree is to delete the database and re-load data into it. The R-Tree doesn't auto-load itself up from the store each time, so you have to handle it manually.

I wonder if we should add an `initialize` function that re-builds the R-Tree index from the data on disk, so that you don't need to rebuild the database on every launch? 

Another option might be to make the RTree implementation pluggable, so that you could e.g. use [flatbush](https://github.com/mourner/flatbush) and serialize the tree to disk. 

I think this would be solvable without any changes if you could get access to the RTree so you could do a bulk load into it directly, but the RTree is encapsulated in the db object that the geospatial plugin uses, and not exposed.

**Comment by dpmcmlxxvi** [comment]
@gkinsman Agreed that exposing the RTree is the simplest solution. Happy to take a PR for it. Otherwise, I will try to get to it when I get a few free cycles.

**Comment by dpmcmlxxvi** [comment]
@gkinsman I created a branch called `feature-add-rtree-api`. If you want to test it out and let me know if that solves your problem. If it does I'll merge and create a new release.

**Comment by gkinsman** [comment]
This works perfectly, thanks so much! I was just getting started and this notification popped up 🥷

**Comment by dpmcmlxxvi** [comment]
Closing with #34. New release is v0.4.0.
